#!/usr/bin/env bash
# LPW: Line Print Wrapper
# Made by Colin Melican <colinmelican@gmail.com>
# https://github.com/kolin63/lpw

function print_help() {
  echo "LPW - Line Print Wrapper"
  echo "usage: lpw [-u config] [-p program] <args>"
  echo ""
  echo "Options:"
  echo "  -u config"
  echo "        Use this config file"
  echo ""
  echo "  args  All other arguments will be passed to the wrapped program"
  echo ""
  echo "Configuration:"
  echo "A config file is checked for at \$HOME/.lpw"
}

if [[ $# -eq 0 ]]; then
  print_help
  exit 0
fi

# external args to be passed to wrapped program
ext_args=""

arg_config="$HOME/.lpw"

# iterate through args
waiting=""
for ((i=1; i<=$#; i++)); do
  arg="${!i}"

  if   [[ "$waiting" == "-u" ]]; then
    arg_config="$arg"
    waiting=""
  elif [[ "$arg" == "-u" ]]; then waiting="$arg"
  else
    ext_args="$ext_args$arg "
  fi
done

# get config file contents
config_text=""
if [[ -e "$arg_config" ]]; then
  config_text="$(cat $arg_config)"
else
  echo "Error: Could not find config file $arg_config"
fi

# parse config file
# TODO: remove any conflicting options
config_args=($config_text)
ext_args_file=""
for ((i=0; i<${#config_args[@]}; i++)); do
  ext_args_file="$ext_args_file${config_args[i]} "
done

# check that there are external args
if [[ "$ext_args" == "" ]]; then
  echo "Error: args required for wrapped printer"
  print_help
  exit 0
fi

set_copies=1
set_pages="all"
set_sides="one-sided"

# TODO: update these variables based on user cli input

# user input loop
while true; do
  # get choice
  echo "1) Copies  [$set_copies]"
  echo "2) Pages   [$set_pages]"
  echo "3) Sides   [$set_sides]"
  echo "4) Custom"
  echo "5) Done"
  echo -n "> "
  read choice

  if [[ choice -eq 1 ]]; then
    input=0
    while [[ ! input -ge 1 ]]; do
      echo "Set amount of copies:"
      echo -n "> "
      read input
    done
    set_copies=$input
  elif [[ choice -eq 2 ]]; then
    input="all"
    echo "Set pages to print (all, odd, even, 3, 3-5)"
    echo -n "> "
    read input
    set_pages=$input
  elif [[ choice -eq 3 ]]; then
    input=0
    while [[ ! input -ge 1 ]] && [[ ! input -le 3 ]]; do
      echo "1) one sided"
      echo "2) two sided, flip on long edge"
      echo "3) two sided, flip on short edge"
      echo -n "> "
      read input
    done
    if   [[ input -eq 1 ]]; then set_sides="one-sided";
    elif [[ input -eq 2 ]]; then set_sides="two-sided-long-edge";
    elif [[ input -eq 3 ]]; then set_sides="two-sided-short-edge";
    fi
  elif [[ choice -eq 4 ]]; then
    echo "Enter an argument to pass to lp"
    echo -n "> "
    read input
    ext_args_file="$ext_args_file$input "
  elif [[ choice -eq 5 ]]; then
    break
  else
    echo "Invalid choice $choice"
  fi
done
